package com.advocate.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CLIENT_TABLE.
 */
public class ClientTable {

    private String userIdClient;
    private String clientFirstName;
    private String clientLastName;
    /** Not-null value. */
    private String caseNumber;
    private String courtNumber;
    private String ClientMobile;
    private String briefDetails;
    private String lawyerId;
    private java.util.Date nextDate;

    public ClientTable() {
    }

    public ClientTable(String userIdClient) {
        this.userIdClient = userIdClient;
    }

    public ClientTable(String userIdClient, String clientFirstName, String clientLastName, String caseNumber, String courtNumber, String ClientMobile, String briefDetails, String lawyerId, java.util.Date nextDate) {
        this.userIdClient = userIdClient;
        this.clientFirstName = clientFirstName;
        this.clientLastName = clientLastName;
        this.caseNumber = caseNumber;
        this.courtNumber = courtNumber;
        this.ClientMobile = ClientMobile;
        this.briefDetails = briefDetails;
        this.lawyerId = lawyerId;
        this.nextDate = nextDate;
    }

    public String getUserIdClient() {
        return userIdClient;
    }

    public void setUserIdClient(String userIdClient) {
        this.userIdClient = userIdClient;
    }

    public String getClientFirstName() {
        return clientFirstName;
    }

    public void setClientFirstName(String clientFirstName) {
        this.clientFirstName = clientFirstName;
    }

    public String getClientLastName() {
        return clientLastName;
    }

    public void setClientLastName(String clientLastName) {
        this.clientLastName = clientLastName;
    }

    /** Not-null value. */
    public String getCaseNumber() {
        return caseNumber;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCaseNumber(String caseNumber) {
        this.caseNumber = caseNumber;
    }

    public String getCourtNumber() {
        return courtNumber;
    }

    public void setCourtNumber(String courtNumber) {
        this.courtNumber = courtNumber;
    }

    public String getClientMobile() {
        return ClientMobile;
    }

    public void setClientMobile(String ClientMobile) {
        this.ClientMobile = ClientMobile;
    }

    public String getBriefDetails() {
        return briefDetails;
    }

    public void setBriefDetails(String briefDetails) {
        this.briefDetails = briefDetails;
    }

    public String getLawyerId() {
        return lawyerId;
    }

    public void setLawyerId(String lawyerId) {
        this.lawyerId = lawyerId;
    }

    public java.util.Date getNextDate() {
        return nextDate;
    }

    public void setNextDate(java.util.Date nextDate) {
        this.nextDate = nextDate;
    }

}
