package com.advocate.database;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FIRM_TABLE.
 */
public class FirmTable {

    /** Not-null value. */
    private String firmName;
    private String userIdFirm;
    private String lawyerIds;

    public FirmTable() {
    }

    public FirmTable(String userIdFirm) {
        this.userIdFirm = userIdFirm;
    }

    public FirmTable(String firmName, String userIdFirm, String lawyerIds) {
        this.firmName = firmName;
        this.userIdFirm = userIdFirm;
        this.lawyerIds = lawyerIds;
    }

    /** Not-null value. */
    public String getFirmName() {
        return firmName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFirmName(String firmName) {
        this.firmName = firmName;
    }

    public String getUserIdFirm() {
        return userIdFirm;
    }

    public void setUserIdFirm(String userIdFirm) {
        this.userIdFirm = userIdFirm;
    }

    public String getLawyerIds() {
        return lawyerIds;
    }

    public void setLawyerIds(String lawyerIds) {
        this.lawyerIds = lawyerIds;
    }

}
